<bbn-tree :source="source"
          uid="id"
          :selection="!!multi"
          @check="checkItem"
          @ready="setChecked"
          @uncheck="uncheckItem"
          @select="selectItem"
          @unselect="unselectItem"
          :scrollable="scrollable"
          ref="tree"
></bbn-tree>
