<bbn-tree :source="source"
          uid="id"
          :checkable="!!multi"
          class="bbn-overlay"
          @check="checkItem"
          @uncheck="uncheckItem"
          @select="selectItem"
          @unselect="unselectItem"
          ref="tree"
></bbn-tree>
